import {cleanup,render,screen,waitFor} from '@testing-library/react';import {MemoryRouter} from 'react-router-dom';import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import App from './App';
const summary={provider:'Yahoo Finance via yfinance',provider_health:'RESEARCH_ONLY',paper_mode:true,research_only:true,market_open:true,data_timestamp:'2026-08-13T10:00:00Z',freshness:{state:'STALE',age_minutes:90,label:'Veri eski: 1,5 saat'},counts:{VERY_STRONG_CANDIDATE:1,STRONG_CANDIDATE:0,CANDIDATE:0,WATCH:0,PENDING_OUTCOMES:19},last_scan:'2026-08-13T10:00:00Z'};
const candidate={symbol:'ASELS',radar_score:91,classification:'VERY_STRONG_CANDIDATE',price:200,rvol:2.5,early_momentum_score:88,timestamp:'2026-08-13T10:00:00Z',data_quality:100,market_regime:'NEUTRAL',daily_trend:'UPTREND',breakout_distance:-.2,disposition:'SIGNAL_UPGRADED'};
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn((url:string)=>Promise.resolve({
  ok:true,
  json:()=>Promise.resolve(url.includes('performance')?{realized_pnl:0,open_positions:0,closed_trades:0,mtm_equity:null}:url.includes('summary')?summary:url.includes('candidates')?[candidate]:url.includes('/ml/status')?{observations:19,fully_labeled:0}:url.includes('system/overview')?{database:'HEALTHY',worker_jobs:[]}:[])
}))) });
afterEach(()=>cleanup());
describe('dashboard',()=>{it('renders radar, stale banner and sorted candidate',async()=>{render(<MemoryRouter><App/></MemoryRouter>);expect(await screen.findByText('Öne Çıkan Adaylar')).toBeInTheDocument();expect(screen.getByText('Veri eski: 1,5 saat')).toBeInTheDocument();expect(screen.getByText('ASELS')).toBeInTheDocument()});it('renders paper portfolio empty-safe',async()=>{render(<MemoryRouter initialEntries={['/portfolio']}><App/></MemoryRouter>);expect(await screen.findByText('Paper Portföy')).toBeInTheDocument();expect(await screen.findByText('Veri yok')).toBeInTheDocument()});it('shows shadow insufficient data warning',async()=>{render(<MemoryRouter initialEntries={['/analysis']}><App/></MemoryRouter>);expect(await screen.findByText(/Henüz yeterli etiketlenmiş veri yok/)).toBeInTheDocument();expect(screen.getByText(/Radar kararını etkilemez/)).toBeInTheDocument()});it('handles provider failure',async()=>{vi.stubGlobal('fetch',vi.fn(()=>Promise.resolve({ok:false,status:503})));render(<MemoryRouter><App/></MemoryRouter>);await waitFor(()=>expect(screen.getByText(/Veri servisine ulaşılamıyor/)).toBeInTheDocument())})});
