import {useEffect,useMemo,useState} from 'react';
import {Link,NavLink,Route,Routes,useParams} from 'react-router-dom';
import {api} from './api';
import type {Bar,Candidate,Detail,Outcome,PaperTrade,TradePlan} from './types';

const trNumber=(n:number,d=2)=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const trDate=(v:string|null|undefined)=>v?new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'Veri yok';
const labels:Record<string,string>={VERY_STRONG_CANDIDATE:'Çok Güçlü Aday',STRONG_CANDIDATE:'Güçlü Aday',CANDIDATE:'Aday',WATCH:'İzle',NO_SIGNAL:'Sinyal Yok',GIRIS_BEKLENIYOR:'Alım İçin Bekle',GIRIS_BOLGESINDE:'Uygun Alım Bölgesinde',BREAKOUT_ONAYI:'Kırılım Gerçekleşti',KACMIS_KOVALAMA:'Geç Kalındı - Alma',GECERSIZ:'İşlem Uygun Değil',HEALTHY:'Çalışıyor',RESEARCH_ONLY:'Araştırma Verisi',CLOSED:'Piyasa Kapalı',OPEN:'Piyasa Açık',IDLE:'Bekliyor',UNKNOWN:'Bilinmiyor',DEGRADED:'Sorunlu',OUTCOME_PENDING:'Sonucu bekleniyor',PARTIALLY_LABELED:'Kısmen sonuçlandı',FULLY_LABELED:'Sonuçlandı'};
const trLabel=(v:string|null|undefined)=>labels[v||'']||v?.replaceAll('_',' ')||'Veri yok';
const nav=[['/','⌁','Radar'],['/signals','◫','Sinyaller'],['/portfolio','◉','Portföy'],['/analysis','⌗','Analiz'],['/system','⚙','Sistem']];
const tourSteps=[
  ['BIST Radar’a hoş geldiniz','Doğrulanmamış araştırma verileriyle çalışan açıklanabilir karar-destek ve paper trading ürünüdür.'],
  ['Radar ekranı','Tamamlanmış barlardan çıkan güçlü adayları, veri yaşını ve piyasa bağlamını tek yerde gösterir.'],
  ['Radar puanı','0–100 bileşik puandır; yüksek puan otomatik alım emri değildir.'],
  ['Sinyaller','Geçmiş adayları, skor gelişimini ve sonuç etiketlerinin durumunu izlersiniz.'],
  ['İşlem planı','Tek al fiyatı yerine giriş bölgesi, breakout, stop ve hedefleri birlikte değerlendirin.'],
  ['Paper Portföy','Gerçek emir olmadan sanal işlemleri ve gerçekleşen performansı gösterir.'],
  ['Analiz','Skor grupları ve sinyal sonuçlarını örneklem büyüklüğüyle birlikte inceler.'],
  ['Shadow Intelligence','ML yalnız diagnostic tahmin üretir; Radar, risk veya işlem kararını değiştiremez.'],
  ['Sistem','Provider, API, veritabanı, worker ve outcome tracker sağlığını gösterir.'],
  ['Research / Paper Only','Bu sistem yatırım tavsiyesi değildir. Gecikmeli veriyle gerçek emir göndermez.'],
];

function useLoad<T>(load:()=>Promise<T>,deps:unknown[]=[]){
  const [data,setData]=useState<T>();const [error,setError]=useState('');
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{let live=true;load().then(x=>live&&setData(x)).catch(()=>live&&setError('Veri servisine ulaşılamıyor'));return()=>{live=false}},deps);
  return{data,error};
}
const badge=(c:string)=>c.includes('VERY')?'positive':c.includes('STRONG')?'blue':c==='CANDIDATE'?'amber':'neutral';
const planTone=(s:string)=>s==='GECERSIZ'||s==='KACMIS_KOVALAMA'?'danger':s==='BREAKOUT_ONAYI'||s==='GIRIS_BOLGESINDE'?'positive':'blue';

function Shell(){
  const [tour,setTour]=useState(()=>localStorage.getItem('bist-radar-tour-seen')!=='1');
  return <div className="shell"><aside className="desktop-sidebar"><Brand/><Navigation/><button className="help" onClick={()=>setTour(true)}>ⓘ Yardım / Rehber</button><div className="legal">RESEARCH / PAPER ONLY<br/>Yatırım tavsiyesi değildir.</div></aside><main><Routes><Route path="/" element={<Radar/>}/><Route path="/symbol/:symbol" element={<Stock/>}/><Route path="/signals" element={<Signals/>}/><Route path="/portfolio" element={<Portfolio/>}/><Route path="/analysis" element={<Analysis/>}/><Route path="/system" element={<System/>}/></Routes></main><Bottom/><button className="floating-help" aria-label="Rehberi aç" onClick={()=>setTour(true)}>?</button>{tour&&<Tour onClose={()=>{localStorage.setItem('bist-radar-tour-seen','1');setTour(false)}}/>}</div>;
}
function Brand(){return <div className="brand"><span className="mark">◎</span><div><b>BIST RADAR</b><small>Research Intelligence</small></div></div>}
function Navigation(){return <nav aria-label="Masaüstü ana navigasyon">{nav.map(([to,icon,label])=><NavLink key={to} to={to} end={to==='/' as never}><span aria-hidden="true">{icon}</span>{label}</NavLink>)}</nav>}
function Bottom(){return <nav className="bottom" aria-label="Mobil ana navigasyon">{nav.map(([to,icon,label])=><NavLink key={to} to={to} end={to==='/' as never} aria-label={label}><span aria-hidden="true">{icon}</span><small>{label}</small></NavLink>)}</nav>}
function Tour({onClose}:{onClose:()=>void}){const [step,setStep]=useState(0);const [title,text]=tourSteps[step];return <div className="tourback" role="dialog" aria-modal="true" aria-labelledby="tour-title"><section className="tour"><div className="tourcount">{step+1} / {tourSteps.length}</div><h2 id="tour-title">{title}</h2><p>{text}</p><div className="touractions"><button onClick={onClose}>Atla</button><button disabled={step===0} onClick={()=>setStep(x=>x-1)}>Geri</button><button className="primary" onClick={()=>step===tourSteps.length-1?onClose():setStep(x=>x+1)}>{step===tourSteps.length-1?'Tamamla':'İleri'}</button></div></section></div>}
function Info({label,text}:{label:string;text:string}){return <span className="info" tabIndex={0} aria-label={`${label}: ${text}`}>i<span role="tooltip">{text}</span></span>}
function State({error,empty=false,text}:{error?:string;empty?:boolean;text?:string}){if(error)return <div className="state error">⚠ {error}</div>;if(empty)return <div className="state">{text||'Henüz veri yok'}</div>;return <div className="skeleton" aria-label="Yükleniyor"/>}
function Header({title,subtitle}:{title:string;subtitle:string}){return <header className="pagehead"><div><h1>{title}</h1><p>{subtitle}</p></div><span className="pill">● PAPER MODE</span></header>}

function Radar(){const summary=useLoad(api.summary);const rows=useLoad(api.candidates);const plans=useLoad(api.tradePlans);const [query,setQuery]=useState('');const filtered=useMemo(()=>[...(rows.data||[])].filter(x=>x.symbol.includes(query.toUpperCase())).sort((a,b)=>b.radar_score-a.radar_score),[rows.data,query]);const planMap=Object.fromEntries((plans.data||[]).map(x=>[x.symbol,x]));if(!summary.data)return <State error={summary.error}/>;const s=summary.data;return <><Header title="Radar" subtitle="Gün içi momentum, uygulanabilir plan ve aday görünümü"/><div className={`fresh ${s.freshness.state.toLowerCase()}`}><b>{s.freshness.label}</b><span>{s.provider} · {trDate(s.data_timestamp)}</span></div><div className="warning">Yahoo/yfinance verileri araştırma amaçlı ve doğrulanmamış kaynaktır. <b>PAPER MODE</b></div><section className="metrics">{[['Çok Güçlü','VERY_STRONG_CANDIDATE'],['Güçlü','STRONG_CANDIDATE'],['Aday','CANDIDATE'],['İzlenen','WATCH'],['Bekleyen Sonuç','PENDING_OUTCOMES']].map(([label,key])=><article key={key}><small>{label}</small><strong>{s.counts[key]??0}</strong></article>)}</section><section className="panel"><div className="panelhead"><div><h2>Öne Çıkan Adaylar <Info label="Radar puanı" text="0–100 bileşik karar-destek puanıdır; otomatik alım değildir."/></h2><p>Radar skoruna göre sıralı</p></div><input aria-label="Sembol ara" placeholder="Sembol ara" value={query} onChange={e=>setQuery(e.target.value)}/></div>{rows.error?<State error={rows.error}/>:filtered.length?<CandidateList rows={filtered} plans={planMap}/>:<State empty/>}</section></>}

function CandidateList({rows,plans={}}:{rows:Candidate[];plans?:Record<string,TradePlan>}){return <><div className="desktop-table"><table><thead><tr><th>Sembol</th><th>Radar</th><th>Sınıf</th><th>Fiyat</th><th>RVOL <Info label="RVOL" text="Normal işlem hacmine göre mevcut hacim. Kazanç yüzdesi değildir."/></th><th>Momentum</th><th>Plan</th><th>Veri zamanı</th></tr></thead><tbody>{rows.map(x=><tr key={x.signal_id||x.symbol}><td><Link to={`/symbol/${x.symbol}`}><b>{x.symbol}</b></Link></td><td><span className="score">{x.radar_score}</span></td><td><span className={`tag ${badge(x.classification)}`}>{trLabel(x.classification)}</span></td><td>{trNumber(x.price)}</td><td>{trNumber(x.rvol)}x</td><td>{x.early_momentum_score}</td><td><PlanBadge plan={plans[x.symbol]}/></td><td>{trDate(x.timestamp)}</td></tr>)}</tbody></table></div><div className="mobile-signals">{rows.map(x=><article className="signal-card" key={x.signal_id||x.symbol}><Link className="card-link" aria-label={`${x.symbol} detayını aç`} to={`/symbol/${x.symbol}`}><span><strong>{x.symbol}</strong><small>{trLabel(x.classification)}</small></span><span className="score">{x.radar_score}</span></Link><dl><dt>Fiyat</dt><dd>{trNumber(x.price)}</dd><dt>RVOL</dt><dd>{trNumber(x.rvol)}x</dd><dt>Momentum</dt><dd>{x.early_momentum_score}</dd></dl><PlanBadge plan={plans[x.symbol]}/>{plans[x.symbol]?.entry_zone_low!=null&&<details><summary>İşlem planını göster</summary><dl><dt>Alım bölgesi</dt><dd>{trNumber(plans[x.symbol].entry_zone_low!)}–{trNumber(plans[x.symbol].entry_zone_high!)}</dd><dt>Stop</dt><dd>{trNumber(plans[x.symbol].stop_price!)}</dd>{plans[x.symbol].targets?.map((t,i)=><><dt key={`l${i}`}>Hedef {i+1}</dt><dd key={`v${i}`}>{trNumber(t.price)}</dd></>)}</dl></details>}</article>)}</div></>}
function PlanBadge({plan}:{plan?:TradePlan}){return plan?<span className={`tag ${planTone(plan.status)}`}>{trLabel(plan.status)}</span>:<span className="tag neutral">İşlem Uygun Değil</span>}

function TradePlanCard({plan}:{plan:TradePlan}){if(plan.reference_price==null)return <section className="panel trade-plan"><h2>İşlem Planı</h2><State empty text={plan.explanation[0]||'Henüz yeterli bağlam yok'}/></section>;const targets=plan.targets||[];return <section className="panel trade-plan"><div className="panelhead"><div><h2>İşlem Planı <Info label="Giriş bölgesi" text="Tek bir anlık fiyat yerine kontrollü alım için izlenen fiyat aralığıdır."/></h2><p>Alım, risk ve kâr alma seviyeleri</p></div><PlanBadge plan={plan}/></div>{plan.stale&&<div className="warning dangertext">Veri eski: {trNumber(plan.data_age_minutes||0,0)} dk. Bu plan yalnız son tamamlanmış araştırma verisine dayanır.</div>}<div className="plan-primary"><Metric label="Alım" value={`${trNumber(plan.entry_zone_low!)} – ${trNumber(plan.entry_zone_high!)}`}/><Metric label="Stop" value={`${trNumber(plan.stop_price!)} / -%${trNumber(plan.stop_distance_percent!)}`} tone="stop"/><Metric label="Hedef 1" value={targets[0]?`${trNumber(targets[0].price)} / +%${trNumber(targets[0].return_percent)}`:'Veri yok'} tone="target"/></div><div className="plan-grid">{targets.slice(1).map((x,i)=><Metric key={x.price} label={`Hedef ${i+2}`} value={`${trNumber(x.price)} / +%${trNumber(x.return_percent)}`} tone="target"/>)}<Metric label="Risk / Getiri" value={`1:${trNumber(plan.risk_reward!)}`}/><Metric label="Plan Durumu" value={trLabel(plan.status)}/></div>{plan.risk_reward!<2&&<div className="warning">Risk/getiri minimum eşiğin altında.</div>}<div className="grid2"><ul className="reasons">{plan.explanation.map(x=><li key={x}>{x}</li>)}</ul>{plan.position_sizing&&<div className="sizing"><h3>Önerilen pozisyon boyutu <small>(paper/research)</small></h3><p>Varsayılan sermaye: {trNumber(plan.position_sizing.account_equity)} · İzin verilen risk: %{trNumber(plan.position_sizing.max_risk_percent)} / {trNumber(plan.position_sizing.allowed_risk_amount)} TL</p><strong>{plan.position_sizing.estimated_quantity} adet · yaklaşık {trNumber(plan.position_sizing.suggested_position_value)} TL</strong></div>}</div><div className="plan-disclaimer">RESEARCH / PAPER ONLY — Hedefler potansiyel getiridir; garanti veya yatırım tavsiyesi değildir.</div></section>}
function Metric({label,value,tone=''}:{label:string;value?:number|string;tone?:string}){return <div className={`plan-metric ${tone}`}><small>{label}</small><strong>{typeof value==='number'?trNumber(value):value??'Veri yok'}</strong></div>}

function CandleChart({bars,plan}:{bars:Bar[];plan?:TradePlan}){if(!bars.length)return <State empty/>;const levels=[plan?.entry_zone_low,plan?.entry_zone_high,plan?.stop_price,...(plan?.targets?.map(x=>x.price)||[])].filter((x):x is number=>x!=null);const w=800,h=280,min=Math.min(...bars.map(x=>x.low),...levels),max=Math.max(...bars.map(x=>x.high),...levels),y=(v:number)=>20+(max-v)/(max-min||1)*(h-40),step=w/bars.length;return <div className="chart" aria-label="Mum grafiği, işlem planı seviyeleri"><svg viewBox={`0 0 ${w} ${h}`} role="img">{bars.map((b,i)=>{const x=i*step+step/2,up=b.close>=b.open;return <g key={b.timestamp} className={up?'up':'down'}><line x1={x} y1={y(b.high)} x2={x} y2={y(b.low)}/><rect x={x-Math.max(1,step*.28)} y={Math.min(y(b.open),y(b.close))} width={Math.max(2,step*.56)} height={Math.max(1,Math.abs(y(b.open)-y(b.close)))}/></g>})}{plan?.stop_price&&<line className="stopline" x1="0" x2={w} y1={y(plan.stop_price)} y2={y(plan.stop_price)}/>} {plan?.targets?.map(x=><line className="targetline" key={x.price} x1="0" x2={w} y1={y(x.price)} y2={y(x.price)}/>)}</svg><div className="chartlegend">EMA9 / EMA20 / EMA50 / VWAP bağlamı backend açıklamasından gelir · <span>— Stop</span> · <b>— Hedefler</b></div></div>}

function Stock(){const {symbol=''}=useParams();const result=useLoad(()=>api.detail(symbol),[symbol]);const [tab,setTab]=useState('plan');if(!result.data)return <State error={result.error}/>;const d:Detail=result.data,c=d.candidate;return <><Header title={d.symbol} subtitle="Hisse detay, işlem planı ve sinyal gelişimi"/><div className={`fresh ${d.freshness.state.toLowerCase()}`}>{d.freshness.label}</div><div className="tabs" role="tablist">{[['plan','İşlem Planı'],['overview','Teknik Bakış'],['chart','Grafik'],['history','Sinyal Geçmişi'],['outcomes','Sonuçlar'],['shadow','Shadow']].map(([key,label])=><button role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</div>{tab==='overview'&&<section className="metrics">{[['Fiyat',c?trNumber(c.price):'Veri yok'],['Radar',c?`${c.radar_score}/100`:'Veri yok'],['Sınıf',c?trLabel(c.classification):'Veri yok'],['RVOL',c?`${trNumber(c.rvol)}x`:'Veri yok'],['Veri Kalitesi',c?`${trNumber(c.data_quality,0)}/100`:'Veri yok']].map(([a,b])=><article key={a}><small>{a}</small><strong className="compact">{b}</strong></article>)}</section>}{tab==='plan'&&<TradePlanCard plan={d.trade_plan}/>} {tab==='chart'&&<section className="panel"><h2>15 Dakikalık Fiyat</h2><CandleChart bars={d.bars} plan={d.trade_plan}/></section>}{tab==='history'&&<section className="panel"><h2>Sinyal Gelişimi</h2>{d.progression.length?<div className="timeline">{d.progression.map(x=><div key={x.signal_id}><time>{trDate(x.timestamp)}</time><b>{x.radar_score}</b><span>{trLabel(x.disposition||x.lifecycle)}</span></div>)}</div>:<State empty/>}</section>}{tab==='outcomes'&&<section className="panel"><State empty text="Sonucu bekleniyor veya bu görünüm için yeterli etiket yok."/></section>}{tab==='shadow'&&<section className="panel shadow"><h2>SHADOW INTELLIGENCE <Info label="Shadow" text="Bu model Radar kararını, riski veya işlemi değiştiremez."/></h2><State empty text="Henüz yeterli etiketlenmiş veri yok."/></section>}</>}
function Signals(){const result=useLoad(api.signals);const outcomes=useLoad(api.outcomes);const outcomeMap=Object.fromEntries((outcomes.data||[]).map(x=>[String(x.signal_id),x]));return <><Header title="Sinyaller" subtitle="Geçmiş sinyaller ve sonrasında gerçekleşen sonuçlar"/><section className="panel">{!result.data?<State error={result.error}/>:result.data.length?<div className="history-list">{result.data.map(s=><SignalHistory key={s.signal_id} signal={s} outcome={outcomeMap[s.signal_id]}/>)}</div>:<State empty/>}</section></>}
function SignalHistory({signal:s,outcome:o}:{signal:Candidate&{signal_id:string;lifecycle:string};outcome?:Outcome}){const value=(key:string)=>typeof o?.[key]==='number'?`%${trNumber(Number(o[key]))}`:'—';return <article className="history-card"><div><Link to={`/symbol/${s.symbol}`}><strong>{s.symbol}</strong></Link><span className="score">{s.radar_score}</span></div><p>{trDate(s.timestamp)} · Referans {trNumber(s.price)} · {trLabel(s.classification)}</p><div className="outcome-grid">{[['+15 dk','forward_return_15m'],['+30 dk','forward_return_30m'],['+60 dk','forward_return_60m'],['+120 dk','forward_return_120m'],['Gün sonu','forward_return_eod'],['MFE','maximum_favorable_excursion'],['MAE','maximum_adverse_excursion']].map(([l,k])=><Metric key={k} label={l} value={value(k)}/>)}</div><span className="tag neutral">{trLabel(s.lifecycle||'OUTCOME_PENDING')}</span></article>}
function Portfolio(){const result=useLoad(api.performance);const trades=useLoad(api.trades);const d=result.data;const rows=trades.data||[];return <><Header title="Paper Portföy" subtitle="Açık ve kapanmış sanal işlemler"/><div className="warning"><b>PAPER ONLY</b> — Gerçek emir veya broker bağlantısı yoktur.</div>{!d?<State error={result.error}/>:<section className="metrics">{[['Gerçekleşen K/Z',d.realized_pnl],['Açık Pozisyon',d.open_positions],['Kapalı İşlem',d.closed_trades],['Güncel Portföy',d.mtm_equity??'Veri yok']].map(([a,b])=><article key={String(a)}><small>{String(a)}</small><strong>{typeof b==='number'?trNumber(b):String(b)}</strong></article>)}</section>}<TradeSection title="Açık Pozisyonlar" rows={rows.filter(x=>!x.exit_time)}/><TradeSection title="Kapalı İşlemler" rows={rows.filter(x=>Boolean(x.exit_time))}/></>}
function TradeSection({title,rows}:{title:string;rows:PaperTrade[]}){return <section className="panel"><h2>{title}</h2>{rows.length?<div className="trade-list">{rows.map(t=><article key={t.trade_id}><b>{t.symbol}</b><dl><dt>Giriş</dt><dd>{trNumber(t.entry_price)}</dd><dt>Adet</dt><dd>{trNumber(t.position_size,0)}</dd><dt>Maliyet</dt><dd>{trNumber(t.entry_price*t.position_size)} TL</dd><dt>Stop</dt><dd>{trNumber(t.stop_price)}</dd><dt>Hedef 1</dt><dd>{trNumber(t.target_1)}</dd><dt>Hedef 2</dt><dd>{trNumber(t.target_2)}</dd>{t.exit_time&&<><dt>Çıkış</dt><dd>{trNumber(t.exit_price||0)}</dd><dt>Gerçekleşen K/Z</dt><dd>{trNumber(t.net_return)} TL</dd><dt>Neden</dt><dd>{trLabel(t.exit_reason)}</dd></>}</dl>{!t.exit_time&&<p>Güncel araştırma fiyatı yoksa gerçekleşmemiş K/Z uydurulmaz.</p>}</article>)}</div>:<State empty text={`${title} bulunmuyor.`}/>}</section>}
function Analysis(){const ml=useLoad(api.ml);const acc=useLoad(api.accuracy);return <><Header title="Analiz" subtitle="Sinyal sonuçları ve karar vermeyen Shadow Intelligence"/><section className="panel shadow"><div className="panelhead"><div><h2>SHADOW INTELLIGENCE <Info label="Shadow" text="Bu model Radar kararını, riski veya işlemi değiştirmez."/></h2><p>Shadow yalnız gözlem yapar; tahminler işlem kararına dönüşmez.</p></div><span className="tag amber">{String(ml.data?.observations??0)} gözlem</span></div>{!ml.data?<State error={ml.error}/>:<div className="state compact-state">{Number(ml.data.fully_labeled)===0?'Henüz yeterli sonuçlanmış sinyal yok. Gözlem sayısı doğruluk anlamına gelmez.':`${String(ml.data.fully_labeled)} sonuçlanmış gözlem mevcut. Örneklem olgunluğu model doğruluğu değildir.`}</div>}</section><section className="panel"><h2>Skor Grubu Performansı</h2>{!acc.data?<State error={acc.error}/>:acc.data.length?<div className="bucket-grid">{acc.data.map((x,i)=><article key={String(x.bucket??i)}><h3>{String(x.bucket??'Grup')}</h3><dl><dt>Sinyal</dt><dd>{String(x.signals??0)}</dd><dt>Sonuçlanan</dt><dd>{String(x.labeled??0)}</dd><dt>Başarı oranı</dt><dd>{x.plus_1_hit_rate==null?'Yeterli veri yok':`%${trNumber(Number(x.plus_1_hit_rate)*100)}`}</dd><dt>Ortalama MFE</dt><dd>{x.average_mfe==null?'—':`%${trNumber(Number(x.average_mfe))}`}</dd><dt>Ortalama MAE</dt><dd>{x.average_mae==null?'—':`%${trNumber(Number(x.average_mae))}`}</dd></dl></article>)}</div>:<State empty text="Henüz yeterli sonuçlanmış sinyal yok."/>}</section></>}
function System(){const sys=useLoad(api.system);const sum=useLoad(api.summary);const jobs=Array.isArray(sys.data?.worker_jobs)?sys.data.worker_jobs as Record<string,unknown>[]:[];const scan=jobs.find(x=>String(x.job_name).includes('scan'));return <><Header title="Sistem" subtitle="BIST Radar çalışma durumu"/><section className="panel system-board"><Status label="API" value={sys.error?'DEGRADED':'HEALTHY'}/><Status label="Veritabanı" value={String(sys.data?.database||'UNKNOWN')}/><Status label="Veri Kaynağı" value={String(sum.data?.provider_health||'UNKNOWN')}/><Status label="Piyasa" value={sum.data?.market_open?'OPEN':'CLOSED'}/><Status label="Otomatik Tarama" value={String(scan?.status||'IDLE')}/><Status label="Son başarılı tarama" value={trDate(String(scan?.last_success||sum.data?.last_scan||''))}/><Status label="Veri zamanı" value={trDate(sum.data?.data_timestamp)}/></section><section className="panel"><h2>Operasyon Güvenliği</h2><p>Yalnız araştırma ve paper trading. Canlı işlem kapalıdır; Shadow karar vermez.</p></section></>}
function Status({label,value}:{label:string;value:string}){return <div className="status"><span>{label}</span><b className={['HEALTHY','OPEN'].includes(value)?'ok':'muted'}>{trLabel(value)}</b></div>}
export default function App(){return <Shell/>}
