export type Freshness = {
  state: "FRESH" | "DELAYED" | "STALE" | "MARKET_CLOSED" | "UNKNOWN";
  age_minutes: number | null;
  label: string;
};
export type Candidate = {
  signal_id?: string;
  symbol: string;
  radar_score: number;
  classification: string;
  price: number;
  rvol: number;
  early_momentum_score: number;
  timestamp: string;
  data_quality: number;
  market_regime: string;
  daily_trend: string;
  breakout_distance: number;
  disposition: string;
  bist100_member?: boolean;
  action_state?: string;
  score_components?: Record<string, number>;
  rvol_sample_size?: number;
  rvol_baseline?: number | null;
  rvol_quality?: string;
  rvol_is_outlier?: boolean;
};
export type PositionSizing = {
  account_equity: number;
  max_risk_percent: number;
  allowed_risk_amount: number;
  suggested_position_value: number;
  estimated_quantity: number;
  advisory_only: boolean;
};
export type TradeTarget = { price: number; return_percent: number };
export type TradePlan = {
  symbol: string;
  timestamp?: string;
  reference_price?: number;
  entry_zone_low?: number;
  entry_zone_high?: number;
  breakout_trigger?: number;
  stop_price?: number;
  stop_distance_percent?: number;
  targets?: TradeTarget[];
  risk_reward?: number;
  status: string;
  explanation: string[];
  data_age_minutes?: number | null;
  stale?: boolean;
  market_closed?: boolean;
  research_only: boolean;
  position_sizing?: PositionSizing;
};
export type Opportunity = {
  candidate: Candidate;
  plan: TradePlan;
  snapshot_id: string;
  data_timestamp: string | null;
};
export type OpportunityReadModel = {
  snapshot_id: string;
  data_timestamp: string | null;
  opportunities: Opportunity[];
};
export type Summary = {
  provider: string;
  provider_health: string;
  paper_mode: boolean;
  research_only: boolean;
  market_open: boolean;
  data_timestamp: string | null;
  freshness: Freshness;
  counts: Record<string, number>;
  last_data_update?: string | null;
  last_provider_attempt?: string | null;
  last_scan: string | null;
};
export type Signal = Candidate & {
  signal_id: string;
  lifecycle: string;
  signal_timestamp?: string;
  reference_price?: number;
  radar_class?: string;
  score_bucket?: string;
  has_trade_plan_snapshot?: boolean;
  trade_plan_snapshot?: TradePlan;
  outcomes?: Record<string, Record<string, unknown>>;
  audit?: Record<string, unknown>;
  shadow_prediction?: Record<string, unknown> | null;
};
export type Bar = {
  timestamp: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
};
export type Detail = {
  symbol: string;
  candidate: Candidate | null;
  bars: Bar[];
  progression: Signal[];
  freshness: Freshness;
  trade_plan: TradePlan;
  universe_metadata?: {
    universe: string;
    company_name?: string;
    market?: string;
    provider: string;
    provider_status: string;
    validation_status: string;
  } | null;
};
export type Outcome = Record<string, unknown> & {
  signal_id?: string;
  symbol?: string;
  timestamp?: string;
  price?: number;
  radar_score?: number;
  lifecycle?: string;
  horizon?: string;
  forward_return?: number;
  maximum_favorable_excursion?: number;
  maximum_adverse_excursion?: number;
};
export type PaperTrade = {
  trade_id: string;
  symbol: string;
  entry_time: string;
  entry_price: number;
  position_size: number;
  stop_price: number;
  target_1: number;
  target_2: number;
  exit_time?: string | null;
  exit_price?: number | null;
  exit_reason?: string | null;
  net_return: number;
};
